name: cjkie
favicon: null
layout_spectrum: 0.3445839984342456
typography_spectrum: 0.4078095145523548
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9e8ce'
    - '#faa175'
    - '#4bb7aa'
    - '#e75440'
    - '#4c4d4d'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
